
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 02 23:55:08 CST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class simbolo2 {
  /* terminals */
  public static final int aescenarios = 2;
  public static final int etiqc = 30;
  public static final int aextras = 7;
  public static final int abonus = 9;
  public static final int etiqa = 29;
  public static final int aheroes = 4;
  public static final int apersonajes = 3;
  public static final int coma = 26;
  public static final int cparedes = 16;
  public static final int abombas = 10;
  public static final int numero = 32;
  public static final int parentc = 25;
  public static final int parenta = 24;
  public static final int nombrefo = 33;
  public static final int cbonus = 19;
  public static final int ameta = 11;
  public static final int cextras = 17;
  public static final int cescenarios = 12;
  public static final int cheroes = 14;
  public static final int cpersonajes = 13;
  public static final int aarmas = 8;
  public static final int igual = 28;
  public static final int cbombas = 20;
  public static final int EOF = 0;
  public static final int pycoma = 27;
  public static final int cmeta = 21;
  public static final int aparedes = 6;
  public static final int error = 1;
  public static final int cvillanos = 15;
  public static final int carmas = 18;
  public static final int avillanos = 5;
  public static final int dimension = 22;
  public static final int dpts = 23;
  public static final int oracion = 31;
}

