
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 02 17:56:02 CST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class simbolo {
  /* terminals */
  public static final int cconfig = 6;
  public static final int nombre = 10;
  public static final int cfigure = 8;
  public static final int tmeta = 19;
  public static final int tarma = 23;
  public static final int tvillano = 15;
  public static final int tipo = 13;
  public static final int theroe = 14;
  public static final int coma = 26;
  public static final int adesign = 5;
  public static final int descripcion = 16;
  public static final int numero = 33;
  public static final int creditos = 18;
  public static final int nombrefo = 32;
  public static final int tbonus = 22;
  public static final int abackground = 3;
  public static final int sstring = 34;
  public static final int adireccion = 29;
  public static final int igual = 28;
  public static final int imagen = 11;
  public static final int cdesign = 9;
  public static final int EOF = 0;
  public static final int pycoma = 27;
  public static final int destruir = 17;
  public static final int vida = 12;
  public static final int aconfig = 2;
  public static final int error = 1;
  public static final int afigure = 4;
  public static final int astring = 30;
  public static final int tbloque = 21;
  public static final int tbomba = 20;
  public static final int llavec = 25;
  public static final int cbackground = 7;
  public static final int llavea = 24;
  public static final int oracion = 31;
}

